name: pidgin
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

confinement: strict

parts:
  pidgin:
    plugin: meson
    source: https://bitbucket.org/pidgin/main
    source-type: git
    build-packages:
    - libgtk-3-dev
    stage-packages:
    - libgtk-3-0

apps:
  pidgin:
    command: bin/pidgin
    plugs:
    - desktop
    - desktop-legacy
    - network
    - network-bind
    - x11
    - wayland